[package]
name = "belajar-rust-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
redis = { version = "0.32.5", features = ["tokio-comp"] }
tokio = { version = "1.47.1", features = ["full"] }
