[package]
name = "belajar-rust-database"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
futures = "0.3.31"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "chrono", "mysql"] }
tokio = { version = "1.47.1", features = ["full"] }
